server:
  port: 9091
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://cm01:8761/eureka/,http://cm02:8761/eureka/  # 设置服务注册中心地址，指向另一个注册中心 ，结构是一定的：http://{hostname}:{port}/eureka/

