server:
  port: 9090
#  servlet:
#    context-path: /eureka-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://cm01:8761/eureka/,http://cm02:8761/eureka/  # 设置服务注册中心地址，指向另一个注册中心
