#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/anan_oa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
#  jpa:
#    show-sql: true
#  jackson:
#    default-property-inclusion: ALWAYS
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: true
#
#  aop:
#    auto: true # Add @EnableAspectJAutoProxy.
#    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as
##  security:
##    user:
##      name: root
##      password: root

server:
  port: 8761
  servlet:
    context-path: /  # 集群 这里 非/ 的话会出现eureka中没有互相注册，没有服务注册的情况

eureka:
  instance:
    hostname: eureka1  # 设置eureka实例名称，与配置文件的变量为主
  client:
    service-url:
      defaultZone: http://eureka2:8761/eureka/  # 设置服务注册中心地址，指向另一个注册中心 ，结构是一定的：http://{hostname}:{port}/eureka/

#eureka:
#  client:
#    register-with-eureka: false # 是否将自己注册到 eureka-server 中，默认为true。否则eureka会一直尝试自己注册自己，导致异常
#    fetch-registry: false # 是否从 eureka-server 中获取服务注册信息，默认为true


